### ISSUE TITLE
There should be link to other posts at the bottom of the blog post. just like all blogging tools for better SEO cross linking.

### ISSUE THREAD

**Issue by Ymanawat** [Hashnode/starter-kit#101]

**Comment by pizofreude** [comment]
I second this for better reach and organic traffic flow.

**Comment by Harsh062** [comment]
Thank you for your suggestion!

The starter-kit currently supports three themes: `personal`, `enterprise`, and `hashnode`. At present, the `hashnode` theme includes a `MORE ARTICLES` section that facilitates cross-linking between posts, which can help with user engagement and SEO.

However, the `personal` and `enterprise` themes do not have this feature by default. This design choice allows users who prefer these themes the flexibility to customize their blog as they see fit. If someone wants to add a More Posts section to the personal or enterprise themes, they can easily do so by utilizing our GraphQL APIs to fetch and display related posts in their desired format.

For users who specifically want built-in cross-linking functionality, we recommend using the `hashnode` theme. This way, we provide flexibility and options for different use cases and preferences.

We appreciate your feedback and are always open to further discussions on how to enhance our themes. Please let us know if you have any other suggestions or questions!

Best regards,
Harsh

**Comment by pizofreude** [comment]
@Harsh062 where do we find the settings to change from `personal` to `hashnode` theme?
