### ISSUE TITLE
[Personal theme] Code Output and Live Demo does not match

### ISSUE THREAD

**Issue by vikas5914** [Hashnode/starter-kit#109]
Hi.

The personal theme demo (https://sandeep.dev/blog) and the code (https://github.com/Hashnode/starter-kit/tree/main/packages/blog-starter-kit/themes/personal) output does not match.  

I went with the personal ones because of the live demo output. I was disappointed that the production was different, and there was no information on achieving the look. The Live demo's code is also not available on GitHub.

**Comment by namnguyenthanhwork** [comment]
I think it is simple to customize, similar to a personal theme demo. You can clone your personal theme, create blog.tsx in the page folder, and mode all code in index.tsx to blog.tsx. After that, you open DevTool and check the structure, styling in the header and homepage, and create anything you want to do.

**Comment by vikas5914** [comment]
@namnguyenthanhwork 
My point is that it should be considered something other than the demo of this repo. Instead, that URL should be moved to the `Example company blogs built with Headless` part of the README.

**Comment by namnguyenthanhwork** [comment]
It's okay. I think you should join discord server and ask them, you can receive your reply quickly.

**Comment by Harsh062** [comment]
Hi @vikas5914,

Thank you for bringing this to our attention. We've updated the demo link in the README for the personal theme to point to a blog that matches the code exactly as provided in the repository.

You can check out the updated demo here: [New Demo Link](https://starter-diopgk410-hashnode-prod.vercel.app/blog)

This should now give you a more accurate representation of the personal theme as it appears right out of the box.

Best regards,
Harsh
