### ISSUE TITLE
Build fails for the personal starter kit----HASHNODE template

### ISSUE THREAD

**Issue by mike-rambil** [Hashnode/starter-kit#113]
## The build doesn't fail for any other templates except for the hashnode theme....

Hashnode theme is the only build thats failing here. Every other theme is working..

## Am I doing something wrong here?

![image](https://github.com/Hashnode/starter-kit/assets/114773646/1c6c53c1-ab1a-40b3-b02b-6d79ab2c6dbf)

**Comment by JannikWempe** [comment]
This should be fixed now.

**Comment by mike-rambil** [comment]
Thank you!

**Comment by mike-rambil** [comment]
There are more errors now.....Hopefully you take care of all of these..
