### ISSUE TITLE
Public access to feature Advanced analytics (beta)

### ISSUE THREAD

**Issue by rommansabbir** [Hashnode/starter-kit#123]
I'm unsure whether it's a bug or not, but the new _[Advanced analytics (beta)]_ feature is publicly accessible.

**Comment by Harsh062** [comment]
Hi @rommansabbir,

Thank you for bringing this to our attention.

Currently, the new Advanced Analytics (Beta) feature is designed to be publicly accessible. This aligns with how our analytics have traditionally been shareable.

However, we understand the importance of privacy and are planning to introduce a configurable option that will allow users to set the analytics to private by default. This upcoming enhancement will give you more control over who can access your analytics data.

We appreciate your feedback and are continuously working to improve our features to better serve our users.

Best regards,
Harsh

**Comment by rommansabbir** [comment]
That's awesome!
