### ISSUE TITLE
Personal Blog Ikigai Theme Repo & Demo Details

### ISSUE THREAD

**Issue by pravintargaryen** [Hashnode/starter-kit#157]
Hi @Harsh062, 

Thank you for choosing to feature this theme in Hashnode's Repo. It's been such an honor. Here's the details of the repo and live demo.

Live Demo : https://pravinreacts.vercel.app/
Repo : https://github.com/pravintargaryen/starter-kit

Regards,
Pravin

**Comment by Harsh062** [comment]
Hi @pravintargaryen,

Thank you for submitting the theme links. We have now added the Minimalist (Ikigai) theme to the `Community Themes` section of the `README` of the starter-kit.
