### ISSUE TITLE
Starter-Kit hashnode theme missing dark mode and other features

### ISSUE THREAD

**Issue by ValentinoZA** [Hashnode/starter-kit#197]
Hi,

The hashnode theme in the starter kit is missing the dark-mode toggle and other features in [https://datazip.io/blog?utm_source=hashnode&utm_medium=github&utm_campaign=promotional](url) see attached my blog page deployed using the hashnode templated.

I also attached the deployment data.

[DeploymentData.txt](https://github.com/user-attachments/files/18165688/DeploymentData.txt)

![starter-kit](https://github.com/user-attachments/assets/ce47e1e8-ae04-4bb9-8090-2942a7090317)

Regards,

**Comment by jomefavourite** [comment]
Hello @valentino_x14, thank you for submitting an issue. However, we encourage you to make the necessary changes yourself, while using headless mode, so I'm closing this issue.2
