### ISSUE TITLE
feat: Add readTimeInMinutes to post header

### ISSUE THREAD

**Issue by arnabsen1729** [Hashnode/starter-kit#30]
Both the enterprise and the personal blog templates don't have the read time displayed. It will be good to have it shown in the PostHeader.

Before
<img width="296" alt="image" src="https://github.com/Hashnode/starter-kit/assets/51032928/f444f31e-a2c5-499e-a700-dff1db57aa71">

After
<img width="550" alt="image" src="https://github.com/Hashnode/starter-kit/assets/51032928/6dbb81fd-1f92-4f8f-80b3-e25084ae1cd2">

**Comment by panda-sandeep** [comment]
Thanks this has been fixed by @unclebay143: https://github.com/Hashnode/starter-kit/pull/31

**Comment by arnabsen1729** [comment]
Awesome !!
