### ISSUE TITLE
Mobile menu doesn't working

### ISSUE THREAD

**Issue by miten5** [Hashnode/starter-kit#38]
Hello team,

I tried to access my website on mobile. but the Hamburger icon for the mobile menu doesn't show up.

Thanks

**Comment by unclebay143** [comment]
There's a fix for this here: #39 

<img width="457" alt="image" src="https://github.com/Hashnode/starter-kit/assets/58919619/34a8e2a1-57c0-4a0d-a79e-46e768813d09">

**Comment by panda-sandeep** [comment]
Has been fixed now: https://github.com/Hashnode/starter-kit/pull/39
