### ISSUE TITLE
Flashing Fast Refresh error when using subpath 

### ISSUE THREAD

**Issue by j3ang** [Hashnode/starter-kit#62]
Flashing: Fast Refresh had to perform a full reload.

If using hashnode as the main project and assign the other nextjs app to use subpath. It will not have this flashing problem. 

![CleanShot 2023-12-08 at 23 40 19](https://github.com/Hashnode/starter-kit/assets/16583879/65356baf-6be0-44eb-b1f5-a5e7375e19cb)

**Comment by panda-sandeep** [comment]
This usually happens when NEXT_PUBLIC_BASE_URL env var is set incorrectly. Can you verify if it’s set to /hashnode in your case?
