### ISSUE TITLE
dev script doesn't run next

### ISSUE THREAD

**Issue by blur94** [Hashnode/starter-kit#68]
[next] /bin/sh: next: command not found [next] next start exited with code 127

The above is the error message I get on my terminal

codegen concurrently runs successfully, but next never spins off the project, so no port is assigned.

I deleted my node_modules several times, and the issue still persists. Also, the issue happens for all the packages

**Comment by panda-sandeep** [comment]
Are you running `pnpm dev`? Make sure you have run `ppnm install` before that.

**Comment by rishabkumar7** [comment]
@blur94 Hey, did you follow the instructions on the `README`
- cd into either `packages/blog-starter-kit/themes/enterprise`, or `packages/blog-starter-kit/themes/hashnode` or `packages/blog-starter-kit/themes/personal`
- Copy `.env.example` to `.env.local`
- `pnpm install`
- `pnpm dev`

If you don't have `pnpm` installed, check this out - [https://pnpm.io/installation](https://pnpm.io/installation)

**Comment by blur94** [comment]
Thanks for your help, @panda-sandeep and @rishabkumar7.

But I feel like that part about running it locally should be lifted to the fore a bit. It's easy for someone to overlook it, as it is deep down to the end of the docs.
