### ISSUE TITLE
[Feature] Add Hover to button

### ISSUE THREAD

**Issue by amanr-dev** [Hashnode/starter-kit#76]
Add the Hover effect to Buttons so that they look 🤔 good.

**Comment by akash-singh8** [comment]
Hello @amanr-dev, thank you for reporting this issue. I'm eager to contribute and would like to take on the task of resolving it. Could you assign this issue to me?

**Comment by ashudevcodes** [comment]
Hey, can you briefly explain which buttons you're referring to? There are only two buttons. one in the **Enterprise theme** section labeled **Book a demo**, and the other in **Hashnode theme** labeled **Sign Up**, and both have a hover effect. @amanr-dev

**Comment by amanr-dev** [comment]
> Hey, can you briefly explain which buttons you're referring to? There are only two buttons. one in the **Enterprise theme** section labeled **Book a demo**, and the other in **Hashnode theme** labeled **Sign Up** @amanr-dev

In the `/headless` route, there are many buttons like: `get started`, `contact`, `started for free`, and more...

**Comment by pranay911** [comment]
can u please assign this issue to me?
